FROM python:3.12.2

WORKDIR /code

# Copy dependencies
COPY ./pyproject.toml ./poetry.lock /code/

# Install Poetry and dependencies
RUN pip install --no-cache-dir --upgrade poetry \
    && poetry install --no-root --no-dev

# Copy application code
COPY ./app /code/app

# Expose port
EXPOSE 80

# Run FastAPI with Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
