FROM python:3.12.2

# Set the working directory inside the container
WORKDIR /code

# Copy the pyproject.toml and poetry.lock (if it exists) into the container
COPY ./pyproject.toml /code/pyproject.toml
COPY ./poetry.lock /code/poetry.lock

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Set poetry's virtualenvs to be created inside the project's directory
RUN poetry config virtualenvs.in-project true

# Install dependencies via Poetry
RUN poetry install --no-dev --no-interaction

# Copy the entire app directory into the container
COPY ./app /code/app

# Set the command to run the FastAPI app using uvicorn
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
